import type { Product, Experience, ProductCategory, ExperienceCategory } from "./types";

export const PRODUCT_CATEGORIES: { value: ProductCategory; label: string; emoji: string }[] = [
  { value: "tshirt", label: "Tişört", emoji: "👕" },
  { value: "sapka", label: "Şapka", emoji: "🧢" },
  { value: "hoodie", label: "Sweat & Hoodie", emoji: "🧥" },
  { value: "aksesuar", label: "Aksesuar", emoji: "🎒" },
  { value: "poster", label: "Poster & Baskı", emoji: "🖼️" },
];

export const EXPERIENCE_CATEGORIES: { value: ExperienceCategory; label: string; emoji: string }[] = [
  { value: "yemek", label: "Sanatçıyla Yemek", emoji: "🍽️" },
  { value: "mesaj", label: "Kişiye Özel Mesaj", emoji: "🎂" },
  { value: "backstage", label: "Backstage & Soundcheck", emoji: "🎤" },
  { value: "ders", label: "Birebir Ders", emoji: "🎸" },
  { value: "gorusme", label: "Görüntülü Görüşme", emoji: "📹" },
];

const sizes = (stockMap: Record<string, number>) =>
  Object.entries(stockMap).map(([value, stock]) => ({ label: "Beden", value, stock }));

const colors = (list: [string, number][]) =>
  list.map(([value, stock]) => ({ label: "Renk", value, stock }));

export const products: Product[] = [
  {
    id: "p-001",
    slug: "duman-tour-tisort-siyah",
    type: "product",
    name: "Duman — Stüdyo Tur Tişörtü",
    category: "tshirt",
    artist: "Duman",
    price: 749,
    compareAtPrice: 899,
    currency: "TRY",
    image: "👕",
    badge: "Çok Satan",
    description:
      "%100 organik pamuk, oversize kalıp. Ön göğüste minimal logo, sırtta tur tarih baskısı. Konser gecesi yorgun düşmeyen, terletmeyen kumaş.",
    sizes: sizes({ S: 12, M: 20, L: 18, XL: 7, XXL: 0 }),
    colors: colors([["Siyah", 40], ["Antrasit", 17]]),
    rating: 4.8,
    reviewCount: 214,
    featured: true,
  },
  {
    id: "p-002",
    slug: "festival-snapback-sapka",
    type: "product",
    name: "Bidahaspace Festival Snapback",
    category: "sapka",
    artist: "Bidahaspace",
    price: 549,
    currency: "TRY",
    image: "🧢",
    badge: "Yeni",
    description:
      "Ayarlanabilir snapback şapka, işlemeli logo. Yağmurlu festival sabahları için su itici dış yüzey.",
    colors: colors([["Siyah", 30], ["Krem", 22], ["Neon Yeşil", 9]]),
    rating: 4.6,
    reviewCount: 98,
    featured: true,
  },
  {
    id: "p-003",
    slug: "manga-hoodie-mor",
    type: "product",
    name: "manga — Outline Hoodie",
    category: "hoodie",
    artist: "manga",
    price: 1290,
    compareAtPrice: 1490,
    currency: "TRY",
    image: "🧥",
    description:
      "Fırçalı iç yüzey, ağır gramajlı kapüşonlu sweatshirt. Kol ucunda grup logosu, kapüşon içi desenli astar.",
    sizes: sizes({ S: 6, M: 14, L: 11, XL: 5 }),
    colors: colors([["Mor", 20], ["Siyah", 16]]),
    rating: 4.9,
    reviewCount: 156,
    featured: true,
  },
  {
    id: "p-004",
    slug: "tote-bag-canvas",
    type: "product",
    name: "Konser Tote Çanta",
    category: "aksesuar",
    artist: "Bidahaspace",
    price: 299,
    currency: "TRY",
    image: "🎒",
    description:
      "Kalın kanvas tote çanta, geniş hacim. Plak, dergi ve festival eşyaların için dayanıklı sap.",
    rating: 4.5,
    reviewCount: 64,
  },
  {
    id: "p-005",
    slug: "sezen-aksu-poster-limited",
    type: "product",
    name: "Sezen Aksu — Limited Konser Posteri",
    category: "poster",
    artist: "Sezen Aksu",
    price: 459,
    currency: "TRY",
    image: "🖼️",
    badge: "Limited 500",
    description:
      "Numaralandırılmış, sanatçı onaylı serigrafi baskı poster. 50x70 cm, müze kalitesinde mat kağıt.",
    rating: 5.0,
    reviewCount: 41,
    featured: true,
  },
  {
    id: "p-006",
    slug: "tarkan-classic-tisort-beyaz",
    type: "product",
    name: "Tarkan — Classic Logo Tişört",
    category: "tshirt",
    artist: "Tarkan",
    price: 649,
    currency: "TRY",
    image: "👕",
    description: "Regular kalıp, yumuşak süprem kumaş. Göğüste retro logo baskısı.",
    sizes: sizes({ S: 10, M: 25, L: 22, XL: 14 }),
    colors: colors([["Beyaz", 40], ["Lacivert", 31]]),
    rating: 4.7,
    reviewCount: 132,
  },
  {
    id: "p-007",
    slug: "beanie-bere-antrasit",
    type: "product",
    name: "Kışlık Bere — Dokuma Logo",
    category: "sapka",
    artist: "Bidahaspace",
    price: 379,
    currency: "TRY",
    image: "🧢",
    description: "Akrilik karışım, sıcak tutan örgü bere. Açık hava konserleri için ideal.",
    colors: colors([["Antrasit", 25], ["Bordo", 18], ["Hardal", 12]]),
    rating: 4.4,
    reviewCount: 53,
  },
  {
    id: "p-008",
    slug: "vinyl-plak-cantasi",
    type: "product",
    name: "Plak & Laptop Sırt Çantası",
    category: "aksesuar",
    artist: "Bidahaspace",
    price: 1190,
    currency: "TRY",
    image: "🎒",
    badge: "Yeni",
    description: "Su geçirmez, 15\" laptop bölmeli, plak taşımaya uygun bölümlü şehir çantası.",
    rating: 4.6,
    reviewCount: 29,
  },
];

export const experiences: Experience[] = [
  {
    id: "e-001",
    slug: "sanatciyla-aksam-yemegi",
    type: "experience",
    name: "Sanatçıyla Başbaşa Akşam Yemeği",
    category: "yemek",
    artist: "Sıla",
    price: 12500,
    currency: "TRY",
    image: "🍽️",
    badge: "Premium",
    tagline: "İstanbul'da seçkin bir restoranda, sahnenin değil masanın baş köşesinde.",
    description:
      "Sevdiğin sanatçıyla aynı masada, baş başa bir akşam yemeği. Sohbet, hikâyeler ve belki masada doğaçlama birkaç mısra. Ekip mahremiyetini korur, anı senin kalır.",
    includes: [
      "Seçkin restoranda 2 kişilik rezervasyon",
      "Sanatçı ile ~90 dk özel sohbet",
      "Profesyonel fotoğraf çekimi",
      "İmzalı bir hediye",
    ],
    duration: "≈ 2 saat",
    delivery: "Yüz yüze — İstanbul",
    slotsLeft: 2,
    location: "İstanbul",
    rating: 5.0,
    reviewCount: 18,
    featured: true,
  },
  {
    id: "e-002",
    slug: "dogum-gunu-video-mesaji",
    type: "experience",
    name: "Sevdiğine Özel Doğum Günü Mesajı",
    category: "mesaj",
    artist: "Mabel Matiz",
    price: 1850,
    currency: "TRY",
    image: "🎂",
    badge: "En Sevilen",
    tagline: "İsmini söyleyerek, sana özel kaydedilmiş bir video.",
    description:
      "Sevdiğin kişinin adını, anısını ve dileklerini bize ilet; sanatçı kişiye özel bir kutlama videosu kaydetsin. Doğum günü, evlilik teklifi ya da 'sadece moralini yükselt' — sen söyle, biz çekelim.",
    includes: [
      "60-90 sn kişiye özel video",
      "İsim ve özel notların okunması",
      "HD indirilebilir dosya",
      "İstersen sürpriz teslim planlaması",
    ],
    duration: "60-90 sn video",
    delivery: "Dijital — 5 gün içinde",
    slotsLeft: 14,
    rating: 4.9,
    reviewCount: 326,
    featured: true,
  },
  {
    id: "e-003",
    slug: "backstage-soundcheck-turu",
    type: "experience",
    name: "Backstage & Soundcheck Turu",
    category: "backstage",
    artist: "Duman",
    price: 4200,
    currency: "TRY",
    image: "🎤",
    badge: "Konser Günü",
    tagline: "Konserden önce sahne arkası, soundcheck ve grup ile tanışma.",
    description:
      "Kapılar açılmadan içeri gir. Soundcheck'i izle, sahne arkasını gez, grup üyeleriyle tanış ve hatıra fotoğrafı çektir. Konser bileti dahil değildir; ayrıca alınmalıdır.",
    includes: [
      "Soundcheck izleme",
      "Sahne arkası turu",
      "Grupla tanışma & fotoğraf",
      "Özel backstage pass kartı",
    ],
    duration: "≈ 75 dk",
    delivery: "Yüz yüze — konser mekânı",
    slotsLeft: 6,
    location: "Ankara",
    rating: 4.8,
    reviewCount: 47,
    featured: true,
  },
  {
    id: "e-004",
    slug: "gitar-birebir-ders",
    type: "experience",
    name: "Birebir Online Gitar Dersi",
    category: "ders",
    artist: "Kazım Koyuncu Tribute",
    price: 2400,
    currency: "TRY",
    image: "🎸",
    tagline: "Profesyonel bir müzisyenle 60 dakikalık özel ders.",
    description:
      "Seviyene göre hazırlanmış, birebir online gitar dersi. İster favori bir şarkıyı çalmayı öğren, ister tekniğini geliştir. Ders kaydı sana özel paylaşılır.",
    includes: ["60 dk birebir online ders", "Seviyene özel program", "Ders kaydı", "Alıştırma notaları (PDF)"],
    duration: "60 dk",
    delivery: "Online — randevulu",
    slotsLeft: 9,
    rating: 4.7,
    reviewCount: 73,
  },
  {
    id: "e-005",
    slug: "gorulu-gorusme-15dk",
    type: "experience",
    name: "Sanatçıyla 15 Dakika Görüntülü Görüşme",
    category: "gorusme",
    artist: "Aleyna Tilki",
    price: 3200,
    currency: "TRY",
    image: "📹",
    badge: "Sınırlı",
    tagline: "Hayalini kurduğun o sohbet, ekrandan ekrana.",
    description:
      "15 dakikalık birebir görüntülü görüşme. Soru sor, teşekkür et, anını paylaş. Görüşme için randevu birlikte planlanır.",
    includes: ["15 dk birebir görüntülü görüşme", "Randevu planlaması", "Ekran görüntüsü hatırası"],
    duration: "15 dk",
    delivery: "Online — randevulu",
    slotsLeft: 4,
    rating: 4.9,
    reviewCount: 112,
  },
  {
    id: "e-006",
    slug: "evlilik-teklifi-sahne",
    type: "experience",
    name: "Sahnede Sürpriz Evlilik Teklifi Anonsu",
    category: "mesaj",
    artist: "Manuş Baba",
    price: 5600,
    currency: "TRY",
    image: "💍",
    tagline: "Konser sırasında, binlerce kişinin önünde unutulmaz bir 'evet'.",
    description:
      "Konser akışına özenle yerleştirilen sürpriz bir anons ile sevdiğine sahneden evlilik teklifi. Ekip zamanlamayı, ışığı ve anı seninle birlikte kurgular.",
    includes: ["Sahneden kişiye özel anons", "Kurgulanmış sürpriz zamanlaması", "Video çekimi", "Ön sıra erişimi (2 kişi)"],
    duration: "Konser içi",
    delivery: "Yüz yüze — planlı konser",
    slotsLeft: 1,
    location: "İzmir",
    rating: 5.0,
    reviewCount: 9,
  },
];

export const allItems = [...products, ...experiences];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getExperienceBySlug(slug: string): Experience | undefined {
  return experiences.find((e) => e.slug === slug);
}

export function findItem(slug: string) {
  return allItems.find((i) => i.slug === slug);
}
