import type { Product } from "./types";

/** Masaüstü tasarım dosyalarından otomatik üretilen gerçek görselli ürünler. */
export const designProducts: Product[] = [
  {
    id: "d-ajda-65ab31248925-60",
    slug: "ajda-65ab31248925-60",
    type: "product",
    name: "Ajda Pekkan — Özel Tişört",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 5400,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-65ab31248925-60.jpg",
    description: "Ajda Pekkan özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 140,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-7f218e51677a-62",
    slug: "ajda-7f218e51677a-62",
    type: "product",
    name: "Ajda Pekkan — Özel Tişört",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 7500,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-7f218e51677a-62.jpg",
    description: "Ajda Pekkan özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 133,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-7f5cdfe2ad0d-64",
    slug: "ajda-7f5cdfe2ad0d-64",
    type: "product",
    name: "Ajda Pekkan — Özel Tişört",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 4300,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-7f5cdfe2ad0d-64.jpg",
    description: "Ajda Pekkan özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 99,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-8785-b489694618a2-57",
    slug: "ajda-8785-b489694618a2-57",
    type: "product",
    name: "Ajda Pekkan — Özel Tişört",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 5000,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-8785-b489694618a2-57.jpg",
    description: "Ajda Pekkan özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 220,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-a4a0-9d1022c6c9f2-63",
    slug: "ajda-a4a0-9d1022c6c9f2-63",
    type: "product",
    name: "Ajda Pekkan — Özel Tişört",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 7850,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-a4a0-9d1022c6c9f2-63.jpg",
    description: "Ajda Pekkan özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 238,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-bc27792364d0-61",
    slug: "ajda-bc27792364d0-61",
    type: "product",
    name: "Ajda Pekkan — Özel Tişört",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 5950,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-bc27792364d0-61.jpg",
    description: "Ajda Pekkan özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 199,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-be99-0769c74d535e-58",
    slug: "ajda-be99-0769c74d535e-58",
    type: "product",
    name: "Ajda Pekkan — Özel Tişört",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 4100,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-be99-0769c74d535e-58.jpg",
    description: "Ajda Pekkan özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 109,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-d39208676b7b-59",
    slug: "ajda-d39208676b7b-59",
    type: "product",
    name: "Ajda Pekkan — Özel Tişört",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 5200,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-d39208676b7b-59.jpg",
    description: "Ajda Pekkan özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 233,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-minimal-9",
    slug: "ajda-minimal-9",
    type: "product",
    name: "Ajda Pekkan — Minimal",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 6050,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-minimal-9.jpg",
    description: "Ajda Pekkan özel koleksiyonundan minimal tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 53,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-neon-8",
    slug: "ajda-neon-8",
    type: "product",
    name: "Ajda Pekkan — Neon",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 7750,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-neon-8.jpg",
    description: "Ajda Pekkan özel koleksiyonundan neon tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 98,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-premium1-34",
    slug: "ajda-premium1-34",
    type: "product",
    name: "Ajda Pekkan — Premium",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 7750,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-premium1-34.jpg",
    description: "Ajda Pekkan özel koleksiyonundan premium tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 184,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-premium2-44",
    slug: "ajda-premium2-44",
    type: "product",
    name: "Ajda Pekkan — Premium",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 4800,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-premium2-44.jpg",
    description: "Ajda Pekkan özel koleksiyonundan premium tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 33,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-relax-26",
    slug: "ajda-relax-26",
    type: "product",
    name: "Ajda Pekkan — Relax",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 7300,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-relax-26.jpg",
    description: "Ajda Pekkan özel koleksiyonundan relax tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 108,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajda-x-manifest-a6ba-44caea9de9b",
    slug: "ajda-x-manifest-a6ba-44caea9de9b1-50",
    type: "product",
    name: "Ajda × Manifest — Kolaj",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 5750,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajda-x-manifest-a6ba-44caea9de9b1-50.jpg",
    description: "Ajda Pekkan özel koleksiyonundan kolaj tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 136,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajdaxmanifest-coll-46",
    slug: "ajdaxmanifest-coll-46",
    type: "product",
    name: "Ajda × Manifest — Kolaj",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 7450,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajdaxmanifest-coll-46.jpg",
    description: "Ajda Pekkan özel koleksiyonundan kolaj tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 163,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-ajdaxmanifest-collab-48",
    slug: "ajdaxmanifest-collab-48",
    type: "product",
    name: "Ajda × Manifest — Kolaj",
    category: "tshirt",
    artist: "Ajda Pekkan",
    price: 4250,
    currency: "TRY",
    image: "👕",
    photo: "/products/ajdaxmanifest-collab-48.jpg",
    description: "Ajda Pekkan özel koleksiyonundan kolaj tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 44,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-4packset3-27",
    slug: "manifest-4packset3-27",
    type: "product",
    name: "Ajda × Manifest — Kolaj Paket Set",
    category: "set",
    artist: "Manifest",
    price: 4200,
    currency: "TRY",
    image: "🎁",
    photo: "/products/manifest-4packset3-27.jpg",
    description: "Manifest özel koleksiyonundan kolaj paket set tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 71,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-lwz7flw-47",
    slug: "manifest-lwz7flw-47",
    type: "product",
    name: "Ajda × Manifest — Kolaj",
    category: "tshirt",
    artist: "Manifest",
    price: 5550,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-lwz7flw-47.jpg",
    description: "Manifest özel koleksiyonundan kolaj tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 230,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifestxajda-collab-49",
    slug: "manifestxajda-collab-49",
    type: "product",
    name: "Ajda × Manifest — Kolaj",
    category: "tshirt",
    artist: "Manifest",
    price: 6850,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifestxajda-collab-49.jpg",
    description: "Manifest özel koleksiyonundan kolaj tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 293,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-1f0367e0e064-53",
    slug: "hayko-1f0367e0e064-53",
    type: "product",
    name: "Hayko Cepkin — Özel Tişört",
    category: "tshirt",
    artist: "Hayko Cepkin",
    price: 6900,
    currency: "TRY",
    image: "👕",
    photo: "/products/hayko-1f0367e0e064-53.jpg",
    description: "Hayko Cepkin özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 51,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-6afbf9b09ce0-56",
    slug: "hayko-6afbf9b09ce0-56",
    type: "product",
    name: "Hayko Cepkin — Özel Tişört",
    category: "tshirt",
    artist: "Hayko Cepkin",
    price: 5700,
    currency: "TRY",
    image: "👕",
    photo: "/products/hayko-6afbf9b09ce0-56.jpg",
    description: "Hayko Cepkin özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 166,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-87bdd058cdbd-54",
    slug: "hayko-87bdd058cdbd-54",
    type: "product",
    name: "Hayko Cepkin — Özel Tişört",
    category: "tshirt",
    artist: "Hayko Cepkin",
    price: 7500,
    currency: "TRY",
    image: "👕",
    photo: "/products/hayko-87bdd058cdbd-54.jpg",
    description: "Hayko Cepkin özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 231,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-9273e8a55401-55",
    slug: "hayko-9273e8a55401-55",
    type: "product",
    name: "Hayko Cepkin — Özel Tişört",
    category: "tshirt",
    artist: "Hayko Cepkin",
    price: 4050,
    currency: "TRY",
    image: "👕",
    photo: "/products/hayko-9273e8a55401-55.jpg",
    description: "Hayko Cepkin özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 184,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-afbb-5db0557f53e6-51",
    slug: "hayko-afbb-5db0557f53e6-51",
    type: "product",
    name: "Hayko Cepkin — Özel Tişört",
    category: "tshirt",
    artist: "Hayko Cepkin",
    price: 5250,
    currency: "TRY",
    image: "👕",
    photo: "/products/hayko-afbb-5db0557f53e6-51.jpg",
    description: "Hayko Cepkin özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 150,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-cepkin-oversized1-43",
    slug: "hayko-cepkin-oversized1-43",
    type: "product",
    name: "Hayko Cepkin — Oversize",
    category: "tshirt",
    artist: "Hayko Cepkin",
    price: 4800,
    currency: "TRY",
    image: "👕",
    photo: "/products/hayko-cepkin-oversized1-43.jpg",
    description: "Hayko Cepkin özel koleksiyonundan oversize tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 142,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-cepkinset-23",
    slug: "hayko-cepkinset-23",
    type: "product",
    name: "Hayko Cepkin — Set",
    category: "set",
    artist: "Hayko Cepkin",
    price: 7400,
    currency: "TRY",
    image: "🎁",
    photo: "/products/hayko-cepkinset-23.jpg",
    description: "Hayko Cepkin özel koleksiyonundan set tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 203,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-e80dcd58ac4a-52",
    slug: "hayko-e80dcd58ac4a-52",
    type: "product",
    name: "Hayko Cepkin — Özel Tişört",
    category: "tshirt",
    artist: "Hayko Cepkin",
    price: 6450,
    currency: "TRY",
    image: "👕",
    photo: "/products/hayko-e80dcd58ac4a-52.jpg",
    description: "Hayko Cepkin özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 101,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-hayko-oversized-17",
    slug: "hayko-oversized-17",
    type: "product",
    name: "Hayko Cepkin — Oversize",
    category: "tshirt",
    artist: "Hayko Cepkin",
    price: 5850,
    currency: "TRY",
    image: "👕",
    photo: "/products/hayko-oversized-17.jpg",
    description: "Hayko Cepkin özel koleksiyonundan oversize tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 291,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-haykocepkinsfanset-24",
    slug: "haykocepkinsfanset-24",
    type: "product",
    name: "Hayko Cepkin — Set Fan",
    category: "set",
    artist: "Hayko Cepkin",
    price: 6900,
    currency: "TRY",
    image: "🎁",
    photo: "/products/haykocepkinsfanset-24.jpg",
    description: "Hayko Cepkin özel koleksiyonundan set fan tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 190,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-anime2-11",
    slug: "manifest-anime2-11",
    type: "product",
    name: "Manifest — Anime",
    category: "tshirt",
    artist: "Manifest",
    price: 6750,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-anime2-11.jpg",
    description: "Manifest özel koleksiyonundan anime tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 27,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-casual-28",
    slug: "manifest-casual-28",
    type: "product",
    name: "Manifest — Casual",
    category: "tshirt",
    artist: "Manifest",
    price: 6150,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-casual-28.jpg",
    description: "Manifest özel koleksiyonundan casual tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 41,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-crop2-15",
    slug: "manifest-crop2-15",
    type: "product",
    name: "Manifest — Crop",
    category: "tshirt",
    artist: "Manifest",
    price: 4350,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-crop2-15.jpg",
    description: "Manifest özel koleksiyonundan crop tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 112,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-fan-45",
    slug: "manifest-fan-45",
    type: "product",
    name: "Manifest — Fan",
    category: "tshirt",
    artist: "Manifest",
    price: 6700,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-fan-45.jpg",
    description: "Manifest özel koleksiyonundan fan tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 129,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-girly-19",
    slug: "manifest-girly-19",
    type: "product",
    name: "Manifest — Girly",
    category: "tshirt",
    artist: "Manifest",
    price: 5000,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-girly-19.jpg",
    description: "Manifest özel koleksiyonundan girly tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 17,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-just-a-girl2-20",
    slug: "manifest-just-a-girl2-20",
    type: "product",
    name: "Manifest — Özel Tişört",
    category: "tshirt",
    artist: "Manifest",
    price: 6800,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-just-a-girl2-20.jpg",
    description: "Manifest özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 81,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-kids-2",
    slug: "manifest-kids-2",
    type: "product",
    name: "Manifest — Çocuk",
    category: "tshirt",
    artist: "Manifest",
    price: 6550,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-kids-2.jpg",
    description: "Manifest özel koleksiyonundan çocuk tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 190,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-m6-13",
    slug: "manifest-m6-13",
    type: "product",
    name: "Manifest — Özel Tişört",
    category: "tshirt",
    artist: "Manifest",
    price: 4450,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-m6-13.jpg",
    description: "Manifest özel koleksiyonundan özel tişört tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 150,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-mixed-22",
    slug: "manifest-mixed-22",
    type: "product",
    name: "Manifest — Mixed",
    category: "tshirt",
    artist: "Manifest",
    price: 6400,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-mixed-22.jpg",
    description: "Manifest özel koleksiyonundan mixed tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 113,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-pinkbasic-16",
    slug: "manifest-pinkbasic-16",
    type: "product",
    name: "Manifest — Basic Pembe",
    category: "tshirt",
    artist: "Manifest",
    price: 7550,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-pinkbasic-16.jpg",
    description: "Manifest özel koleksiyonundan basic pembe tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 193,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest-poster-12",
    slug: "manifest-poster-12",
    type: "product",
    name: "Manifest — Poster",
    category: "poster",
    artist: "Manifest",
    price: 6350,
    currency: "TRY",
    image: "🖼️",
    photo: "/products/manifest-poster-12.jpg",
    description: "Manifest özel koleksiyonundan poster tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 241,
    featured: true,
  },
  {
    id: "d-manifest-vip-merch2-14",
    slug: "manifest-vip-merch2-14",
    type: "product",
    name: "Manifest — VIP",
    category: "tshirt",
    artist: "Manifest",
    price: 6650,
    currency: "TRY",
    image: "👕",
    photo: "/products/manifest-vip-merch2-14.jpg",
    description: "Manifest özel koleksiyonundan vip tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 291,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-manifest3packset1-25",
    slug: "manifest3packset1-25",
    type: "product",
    name: "Manifest — Paket Set",
    category: "set",
    artist: "Manifest",
    price: 5300,
    currency: "TRY",
    image: "🎁",
    photo: "/products/manifest3packset1-25.jpg",
    description: "Manifest özel koleksiyonundan paket set tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 287,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-4packlux-33",
    slug: "mnfst-4packlux-33",
    type: "product",
    name: "Manifest — Paket Set Lux",
    category: "set",
    artist: "Manifest",
    price: 5500,
    currency: "TRY",
    image: "🎁",
    photo: "/products/mnfst-4packlux-33.jpg",
    description: "Manifest özel koleksiyonundan paket set lux tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 196,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-brown-42",
    slug: "mnfst-brown-42",
    type: "product",
    name: "Manifest — Kahve",
    category: "tshirt",
    artist: "Manifest",
    price: 7800,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-brown-42.jpg",
    description: "Manifest özel koleksiyonundan kahve tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 215,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-casual3-30",
    slug: "mnfst-casual3-30",
    type: "product",
    name: "Manifest — Casual",
    category: "tshirt",
    artist: "Manifest",
    price: 6100,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-casual3-30.jpg",
    description: "Manifest özel koleksiyonundan casual tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 23,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-casuallux-31",
    slug: "mnfst-casuallux-31",
    type: "product",
    name: "Manifest — Lux Casual",
    category: "tshirt",
    artist: "Manifest",
    price: 6500,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-casuallux-31.jpg",
    description: "Manifest özel koleksiyonundan lux casual tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 84,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-csllux-32",
    slug: "mnfst-csllux-32",
    type: "product",
    name: "Manifest — Lux Casual",
    category: "tshirt",
    artist: "Manifest",
    price: 6650,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-csllux-32.jpg",
    description: "Manifest özel koleksiyonundan lux casual tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 102,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-dark4-41",
    slug: "mnfst-dark4-41",
    type: "product",
    name: "Manifest — Dark",
    category: "tshirt",
    artist: "Manifest",
    price: 7600,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-dark4-41.jpg",
    description: "Manifest özel koleksiyonundan dark tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 219,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-girly5-40",
    slug: "mnfst-girly5-40",
    type: "product",
    name: "Manifest — Girly",
    category: "tshirt",
    artist: "Manifest",
    price: 7550,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-girly5-40.jpg",
    description: "Manifest özel koleksiyonundan girly tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 53,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-girlyset-18",
    slug: "mnfst-girlyset-18",
    type: "product",
    name: "Manifest — Set Girly",
    category: "set",
    artist: "Manifest",
    price: 5350,
    currency: "TRY",
    image: "🎁",
    photo: "/products/mnfst-girlyset-18.jpg",
    description: "Manifest özel koleksiyonundan set girly tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 128,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-girlyset4-38",
    slug: "mnfst-girlyset4-38",
    type: "product",
    name: "Manifest — Set Girly",
    category: "set",
    artist: "Manifest",
    price: 5050,
    currency: "TRY",
    image: "🎁",
    photo: "/products/mnfst-girlyset4-38.jpg",
    description: "Manifest özel koleksiyonundan set girly tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 145,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-girlyset6-39",
    slug: "mnfst-girlyset6-39",
    type: "product",
    name: "Manifest — Set Girly",
    category: "set",
    artist: "Manifest",
    price: 7550,
    currency: "TRY",
    image: "🎁",
    photo: "/products/mnfst-girlyset6-39.jpg",
    description: "Manifest özel koleksiyonundan set girly tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 123,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-gorlyset2-37",
    slug: "mnfst-gorlyset2-37",
    type: "product",
    name: "Manifest — Set",
    category: "set",
    artist: "Manifest",
    price: 4750,
    currency: "TRY",
    image: "🎁",
    photo: "/products/mnfst-gorlyset2-37.jpg",
    description: "Manifest özel koleksiyonundan set tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 288,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-manigirl-10",
    slug: "mnfst-manigirl-10",
    type: "product",
    name: "Manifest — Mani Girl",
    category: "tshirt",
    artist: "Manifest",
    price: 6450,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-manigirl-10.jpg",
    description: "Manifest özel koleksiyonundan mani girl tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 220,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-manigirltop-skirt-21",
    slug: "mnfst-manigirltop-skirt-21",
    type: "product",
    name: "Manifest — Mani Girl Etek",
    category: "tshirt",
    artist: "Manifest",
    price: 6100,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-manigirltop-skirt-21.jpg",
    description: "Manifest özel koleksiyonundan mani girl etek tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 174,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-manigrilset",
    slug: "mnfst-manigrilset",
    type: "product",
    name: "Manifest — Set Mani Girl",
    category: "set",
    artist: "Manifest",
    price: 4400,
    currency: "TRY",
    image: "🎁",
    photo: "/products/mnfst-manigrilset.jpg",
    description: "Manifest özel koleksiyonundan set mani girl tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.8,
    reviewCount: 189,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-momnt-6",
    slug: "mnfst-momnt-6",
    type: "product",
    name: "Manifest — Moment",
    category: "tshirt",
    artist: "Manifest",
    price: 4900,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-momnt-6.jpg",
    description: "Manifest özel koleksiyonundan moment tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 207,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-mystc1-7",
    slug: "mnfst-mystc1-7",
    type: "product",
    name: "Manifest — Mystic",
    category: "tshirt",
    artist: "Manifest",
    price: 4200,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-mystc1-7.jpg",
    description: "Manifest özel koleksiyonundan mystic tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 188,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-oversized-crop-4",
    slug: "mnfst-oversized-crop-4",
    type: "product",
    name: "Manifest — Oversize Crop",
    category: "tshirt",
    artist: "Manifest",
    price: 7600,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-oversized-crop-4.jpg",
    description: "Manifest özel koleksiyonundan oversize crop tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 135,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-ovrszd-5",
    slug: "mnfst-ovrszd-5",
    type: "product",
    name: "Manifest — Oversize",
    category: "tshirt",
    artist: "Manifest",
    price: 4250,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-ovrszd-5.jpg",
    description: "Manifest özel koleksiyonundan oversize tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 248,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-pink-crop-1",
    slug: "mnfst-pink-crop-1",
    type: "product",
    name: "Manifest — Crop Pembe",
    category: "tshirt",
    artist: "Manifest",
    price: 6150,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-pink-crop-1.jpg",
    description: "Manifest özel koleksiyonundan crop pembe tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.7,
    reviewCount: 67,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-premiumlux7-35",
    slug: "mnfst-premiumlux7-35",
    type: "product",
    name: "Manifest — Premium Lux Premium",
    category: "tshirt",
    artist: "Manifest",
    price: 5500,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-premiumlux7-35.jpg",
    description: "Manifest özel koleksiyonundan premium lux premium tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.6,
    reviewCount: 24,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-prmlx4-36",
    slug: "mnfst-prmlx4-36",
    type: "product",
    name: "Manifest — Premium Lux Premium",
    category: "tshirt",
    artist: "Manifest",
    price: 4650,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-prmlx4-36.jpg",
    description: "Manifest özel koleksiyonundan premium lux premium tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.9,
    reviewCount: 94,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-red2-3",
    slug: "mnfst-red2-3",
    type: "product",
    name: "Manifest — Kırmızı",
    category: "tshirt",
    artist: "Manifest",
    price: 4750,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-red2-3.jpg",
    description: "Manifest özel koleksiyonundan kırmızı tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 221,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
  {
    id: "d-mnfst-tennis-29",
    slug: "mnfst-tennis-29",
    type: "product",
    name: "Manifest — Tenis",
    category: "tshirt",
    artist: "Manifest",
    price: 6150,
    currency: "TRY",
    image: "👕",
    photo: "/products/mnfst-tennis-29.jpg",
    description: "Manifest özel koleksiyonundan tenis tasarım. Sınırlı üretim, lisanslı baskı; premium kumaş ve baskı kalitesi.",
    rating: 4.5,
    reviewCount: 122,
    featured: true,
    sizes: [{ label: "Beden", value: "XS", stock: 8 }, { label: "Beden", value: "S", stock: 18 }, { label: "Beden", value: "M", stock: 28 }, { label: "Beden", value: "L", stock: 24 }, { label: "Beden", value: "XL", stock: 14 }, { label: "Beden", value: "XXL", stock: 6 }],
  },
];
